# Generated by Django 3.2.12 on 2022-02-14 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_instructor',
            new_name='is_lecturer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_learner',
            new_name='is_student',
        ),
    ]
