# Generated by Django 3.2.12 on 2022-02-14 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220214_0239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructor',
            new_name='Lecturer',
        ),
        migrations.RenameModel(
            old_name='Learner',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phonenumber',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_animal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
