# Generated by Django 3.2.12 on 2022-02-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20220214_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default='24-06-1997'),
        ),
    ]
