# Generated by Django 3.2.12 on 2022-02-16 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_profile_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='LearnerAnswer',
            new_name='StudentAnswer',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='interest',
            field=models.ManyToManyField(related_name='more_locations', to='pages.Topic'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.topic'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='pages.topic'),
        ),
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(related_name='interested_learners', to='pages.Topic'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pages.topic'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
