# Generated by Django 3.2.12 on 2022-02-24 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_topic_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takenquiz',
            old_name='learner',
            new_name='student',
        ),
    ]
