# Generated by Django 3.2.12 on 2022-02-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20220224_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='thumb',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
