# Generated by Django 3.2.12 on 2022-02-28 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20220228_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pages.tutorial'),
        ),
    ]
