# Generated by Django 3.2.12 on 2022-02-28 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_comments_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='course',
        ),
        migrations.AddField(
            model_name='notes',
            name='tutorial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.tutorial'),
            preserve_default=False,
        ),
    ]
