# Generated by Django 3.2.12 on 2022-02-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_notes_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='title',
        ),
    ]
