# Generated by Django 3.2.12 on 2022-02-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_remove_notes_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interests',
        ),
    ]
